apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pyracms-templates
  name: pyracms-templates
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
