apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pyracms
  name: pyracms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyracms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pyracms
    spec:
      containers:
      - image: pynguins/pyracms:latest
        imagePullPolicy: ""
        name: pyracms
        ports:
        - containerPort: 6543
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/lib/python3.7/site-packages/pyracms-0.0-py3.7.egg/pyracms/static
          name: pyracms-static
        - mountPath: /usr/local/lib/python3.7/site-packages/pyracms-0.0-py3.7.egg/pyracms/templates
          name: pyracms-templates
        - mountPath: /code/db
          name: pyracms-database
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: pyracms-static
        persistentVolumeClaim:
          claimName: pyracms-static
      - name: pyracms-templates
        persistentVolumeClaim:
          claimName: pyracms-templates
      - name: pyracms-database
        persistentVolumeClaim:
          claimName: pyracms-database
status: {}
